import { Container } from "@resonance/ui";
import { Metadata } from "next";
import { GuestGuard } from "@/shared/providers/guest-guard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GuestGuard>
      <Container className="bg-background">{children}</Container>
    </GuestGuard>
  );
}
